### ISSUE TITLE
Ignore parameter values out of range

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/arduino#190] opened 2024-06-27 00:38 UTC
It seems the PMS5003T seldomly sends extremely low values.

See:
https://github.com/home-assistant/core/issues/120586

I would suggest when reading values from sensor we accept only the following ranges:

Temperature: -40°C to 125°C
Relative Humidity: 0% - 100%
CO2: 0-10.000ppm
PM1, 2.5, 10: 0 - 1000 ug/m3

**Comment by Byter09** [comment] 2024-06-27 07:44
There seems to be a pattern to this though. Every time my temperature goes to `-1000.99`, the PM sensors also go to `-1 µg/m³` or `particles/dL` for the 0.3 PM sensor. The humidity sensor also goes to -1%.

I do not observe this behaviour with the CO2 value, however I'm sure it can't hurt to limit it to sane values as well :)


What I'm trying to say is that maybe there's something that triggers these values to happen at the same time. Let me know if there's anything I can do to help diagnose this.

**Comment by airgradienthq** [comment] 2024-07-01 05:53
@Byter09 Yes that makes sense. The temperature/humidity in the outdoor monitor comes from the PM sensor. So that PM/temperature/humidity fails at the same time indicates a com problem.

**Comment by Byter09** [comment] 2024-07-01 06:37
Here's one more weird quirk I noticed. My internet was off over the night (maintenance by my ISP) until a few minutes ago.

In that whole time, instead of spiking once per day, it spiked several times. I have the feeling this might somehow be related to it not being able to reach the server? Maybe it restarts and the initial value is weird? I don't know. Just leaving this here in the hope that it helps

![Screenshot_2024-07-01-08-32-49-80_c3a231c25ed346e59462e84656a70e50](https://github.com/airgradienthq/arduino/assets/16060697/11a4d6e6-356b-437e-90f6-9b851c001e9e)

**Comment by mhlas7** [comment] 2024-07-11 16:26
Adding another data point here, I turned off "Post Data to AirGradient" two days in Home Assistant (my sensor is set to local control, not cloud) and I now see the temp read -840 F for a two hour period at least once per day. Before I turned it off, I was getting one off spikes down to -840 F similar to other users in this thread. This makes me think the post data to AirGradient function has some sort of impact on the temp reading.

![image](https://github.com/airgradienthq/arduino/assets/3398654/4c61e8cb-d071-401d-815b-8bcb6a79de77)

**Comment by gslender** [comment] 2024-07-22 08:58
Yep, from looking at the data I have, it looks to occur during period of when the sensor is updating to AirGradient in the cloud. Is it possible the internal serial read from the sensor is failing to occur when it should, and bad values are being read instead??

**Comment by michaelpeterswa** [comment] 2024-07-22 17:58
Seeing a similar pattern, posting to AirGradient is enabled, and all data collection for this graph is happening via the local API. 
![image](https://github.com/user-attachments/assets/67c5b4c1-cacf-4e3f-a280-b4cd87eebddf)

If there's anything I can do to assist just let me know.

**Comment by pnt325** [comment] 2024-08-26 13:53
The issue is fixed by #197. Please open issue again if still problem.

**Closed by pnt325** 2024-08-26 13:53 UTC

**Comment by dfsmith** [comment] 2024-09-01 03:28
My (new) outdoor Airgradient went funny when I moved it from inside to outside.  I suspect this might be a power issue, and will play with capacitors.
![image](https://github.com/user-attachments/assets/4147f78a-2a30-4aff-abe9-b156c244b5e4)

**Comment by Byter09** [comment] 2024-09-01 08:13
@dfsmith I had something similar happen when the wire wasn't completely attached. Maybe give that a try? Though in my case the sensor reported other values fine, so maybe figure out which of the sensors are behaving weird. If it's all one specific sensor then it's likely the cable.

**Comment by dfsmith** [comment] 2024-09-09 05:13
@Byter09 FYI: 10uF of capacitance on the 3.3V line cleared it right up.  I conjecture that WiFi was stealing too much instantaneous power in the new location, though I didn't collect any hard data to confirm it.

**Comment by BkSouX** [comment] 2024-09-11 07:53
Hi, still had the issue with the air gradient outdoor 

<img width="562" alt="image" src="https://github.com/user-attachments/assets/20c319e7-e7ed-4a8d-a2cb-27d0a1a19a8a">

**Comment by NorthboundPaddler** [comment] 2024-12-03 14:44
Hello - I am still having this issue as well with my O-1PST reporting insane values in Home Assistant. My device is running firmware 3.1.3 and I'll note that the weather here locally is below 0 degrees C, if that matters. If I restart my Home Assistant instance, the values are normal for a few minutes before going well out of range.

Temperature graph is predominantly out of range: 
![image](https://github.com/user-attachments/assets/c1f17a28-da09-4faa-9d11-01260f2f44c5)

Would this be resolved with new firmware? If so, should I use the unified 3.1.9 version or something else?

Thanks for work on this project!

**Comment by samuelbles07** [comment] 2024-12-03 20:26
Hi @NorthboundPaddler , you should use the latest firmware version 3.1.13

**Comment by NorthboundPaddler** [comment] 2024-12-08 02:52
> Hi @NorthboundPaddler , you should use the latest firmware version 3.1.13

I did exactly that today, and it's been working perfectly since I upgraded to this new firmware. Glad that's all it took... I appreciate that you took the time to respond. Cheers!
